### ISSUE TITLE
support for other languages 

### ISSUE THREAD

**Issue by blurymind** [axnospaint/axnospaint-lib#20]
Can we do an english UI? 

one suggestion is to read the user's language via
`var userLang = navigator.language || navigator.userLanguage; `

and if its not japanese or something else supported, set it to english.

You would need to put all translation tokens (app labels) in a single json file.

I would try to PR such a change to this project if the maintainer reviewing it is interested?

**Comment by axnospaint** [comment]
This is a very interesting proposal. However, there are a few issues:

- Due to our limitations, the design is not based on a multilingual UI.
- Compared to general painting tools, the amount of messages is large (we aim to be beginner-friendly).
- Some messages in the `msg()` method of the `axpobj.js` file have exception handling.
- Some messages, such as error messages, are literal.
- We do not want to increase the communication load (file size) with multilingual support (it would be necessary to load only the required JSON files at startup).

If you have good ideas to solve these issues, we would like to support an English UI as well. Thank you for your suggestion.

**Comment by blurymind** [comment]
Hi thank you for your response.
As a start, I aim to only translate what the user sees - the labels in the ui. The error handling is fine in staying in japanese.
So no errors getting logged in dev console are of interest to me for translation at this point.

One suggestion is to have all the labels in a global JSON file.
One for japanese and one for english.

> We do not want to increase the communication load (file size) with multilingual support (it would be necessary to load only the required JSON files at startup).

To do this without increasing the bundle size, I can think of two possible options:
- make the translation a part of the build process - passing a parameter to make it build an english version
- make the library check if a specific localisation json file can be loaded from the public folder where it is hosted - if it can, use it instead of the built in japanese one 
- pass the translation token object (parsed from json) to the library, when it is initialized

I personally like the last option or the last two. Making it a part of the build process would just encourage someone to fork this project and re-distribute an internationalized version in order to make it easier for others to bundle

**Comment by axnospaint** [comment]
Hello,

We discussed this matter with the development team. Unfortunately, none of our team members speak English, so it is difficult for us to create or ensure the quality of translation data (JSON). This means that official support is only available in Japanese, and we cannot assist with updating translation data when new features are added to the tool.

However, we agree to support an interface that loads translation data and reflects it in the tool.

Among the proposed options, we think the following approach is best:

> Check if a specific localization JSON file can be loaded from the public folder where it is hosted - if it can, use it instead of the built-in Japanese one.

To keep the implementation simple, we believe it is better not to support the feature to switch languages in the settings.

If these conditions are acceptable, we would like to proceed with the modifications.

**Comment by blurymind** [comment]
Hi this sounds great :) I think it is acceptable and am happy that it is simple. 
Would be happy to create and maintain an english translation json.

Speaking as someone who lives in the uk for many years now and being bilingual, I can say from experience that this has become the language of multinationals. 
It has sort of become a glue language, allowing us to communicate between each other. A bulgarian can freely talk with someone from poland for example. Most people in Europe speak english, so I believe that it will help make the app accessible to a much gerater pool of people - not just the english or the american - but the rest of the world as a whole

**Comment by axnospaint** [comment]
Thank you for your reply.

Regarding the method of linking JSON files, I think it will be necessary to modify the tool’s data structure. Although I am inexperienced, I have come up with a method that would be convenient for us. I will create a prototype and present it to you. Please wait a few days.

I believe I will need your cooperation for the English translation work as well.

I also plan to use this opportunity to study the language. :)

**Comment by axnospaint** [comment]
#20 English UI prototype

/dist/en.json - Token : English dictionary (created by each user)
/src/text/ja.json - Token: Japanese dictionary (Bundle by Webpack)

* When userLanguage starts with 'en', fetch en.json.
* If en.json does not exist, use Japanese dictionary.
* For words not listed in the English dictionary, refer to the Japanese dictionary.
* Messages and settings screens have not yet been translated.
* The token search and replace logic is poor as I couldn't think of a good way to do it. (I don't want to use eval().)
* Please let me know if there are any unnatural English translations.

**Comment by axnospaint** [comment]
The process of detecting the browser’s language on the library side will be abolished, and the method will be changed to specify the JSON used with the ‘dictionary’ startup option.

```
        document.addEventListener("DOMContentLoaded", function () {
            var axp = new AXNOSPaint({
                bodyId: 'axnospaint_body',
                dictionary: 'en.json',
            });
        });
```

The reason for the change is that it is necessary to inquire which language dictionaries are available on the server. Therefore, it would be simpler to have the server perform the language detection and provide only the results to the library.

**Comment by blurymind** [comment]
thank you for working on this. I will give it a spin this weekend :)

**Comment by blurymind** [comment]
Hi I gave this a try and it looks very good. Some labels are still not translated - the settings tab and post tab are both missing all of the labels in the content area.

Is the mechanism to translate them already there?

The labels that most people will care will be in the canvas tab and they all seem to work. Some of them overflow a bit outside of the button - since their translation requires more characters. Not sure if a simple fix for this would be to reduce the font size as an option

**Comment by axnospaint** [comment]
>Is the mechanism to translate them already there?

We haven’t started yet. The work required for these modifications is enormous, and we don’t have the development resources to carry it out.
We would like to address this as a future task.
If you have any good ideas for improvement, please make a PR.

**Comment by blurymind** [comment]
Hi thank you for clarifying. I would be happy with what is already done so far. It makes the app mostly usable for non japanese speakers.
Would you be ok with merging it before I do any attempts to expand upon it? :)

**Comment by axnospaint** [comment]
Sorry for keeping you waiting.
The merge into the main branch is complete.
#49

**Comment by blurymind** [comment]
Thank you :bow: also for making this a nice commit that can be studied

**Comment by axnospaint** [comment]
As previously mentioned, we support the interface for loading dictionary data but do not provide English UI or English documentation. This decision is made to allocate our development resources where they are truly needed.

>I am guessing this is where we collect translations?
>https://github.com/axnospaint/axnospaint-lib-dictionary

No, it's simply a document explaining how to create dictionary data. We cannot verify the accuracy of translations submitted by multiple users due to resource constraints.

>I am guessing that most people interested in this dictionary repository will be English speakers or bilingual.

You're absolutely right. However, partial translations can lead to misunderstandings or misinterpretations. Ideally, we'd want all documentation, including the library itself, to be accurately translated and kept up-to-date. If you're willing to contribute, please feel free to create a fork.

**Comment by axnospaint** [comment]
Due to no progress for a long time, we will close this issue.
If there is any progress, please create a new issue separately.
